name: Set up macOS environment
description: Set up everything needed to build and release things on macOS
inputs:
  certificates-p12:
    required: true
    description: The certificates to use for codesigning, as a base64-encoded .p12
  certificates-password:
    required: true
    description: The password for the .p12
  keychain-password:
    required: true
    description: The keychain password to use
  aws-access-key-id:
    required: true
    description: The aws-access-key-id used to authenticate with AWS
  aws-secret-access-key:
    required: true
    description: The aws-secret-access-key used to authenticate with AWS
  cloudflare-email:
    required: true
    description: The email used to authenticate with Cloudflare
  cloudflare-token:
    required: true
    description: The token used to authenticate with Cloudflare
runs:
  using: composite
  steps:
    - name: Install the Apple certificates
      env:
        CERTIFICATES_P12: ${{ inputs.certificates-p12 }}
        CERTIFICATES_PASSWORD: ${{ inputs.certificates-password }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain-password }}
      run: |
        echo $CERTIFICATES_P12 | base64 —decode > certificate.p12
        security create-keychain -p <your-password> build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p <your-password> build.keychain
        security import certificate.p12 -k build.keychain -P $CERTIFICATES_PASSWORD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k <your-password> build.keychain
        /usr/bin/codesign --force -s <identity-id> ./path/to/you/app -v
        (
          echo MACOS_CERTID=$(security find-identity -v -p codesigning | grep "Developer ID Application: " | awk '{ print $2 }')
        ) >> $GITHUB_ENV
      shell: bash
    - name: Configure git
      run: |
        git config --global user.name "Frida Developers"
        git config --global user.email "oleavr@frida.re"
      shell: bash
    - name: Clean repos
      run: |
        git fetch origin --prune --prune-tags
        git submodule foreach "git clean -ffdx"
        git submodule foreach "git reset --hard HEAD"
        git submodule foreach "git fetch origin --prune --prune-tags"
      shell: bash
    - name: Check out releng/meson
      run: |
        git submodule init -- releng/meson
        git submodule update --depth 1 -- releng/meson
      shell: bash
    - name: Install Python
      if: runner.arch == 'X64'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set Frida environment variables
      run: |
        (
          echo "FRIDA=$GITHUB_WORKSPACE"
          echo "FRIDA_VERSION=$(releng/frida_version.py)"
        ) >> $GITHUB_ENV
      shell: bash
